import { type ReactNode } from 'react';
import { Link } from 'wouter';
import { ArrowLeft, BadgeCheck, CircleHelp, Compass, Heart, MapPin, MessageCircle, Radio, Sparkles, UserRound, Users, Zap } from 'lucide-react';
import { getGetMyLikesQueryKey, getGetMyMatchesQueryKey, useGetMyLikes, useGetMyMatches } from '@workspace/api-client-react';

function mediaUrl(path: string) {
  if (path.startsWith('http') || path.startsWith('/api/')) return path;
  return `/api/storage${path.startsWith('/') ? path : `/${path}`}`;
}

function LikesFrame({ children }: { children: ReactNode }) {
  return <div className="noise min-h-[100dvh] bg-background"><div className="mx-auto max-w-5xl px-5 py-6 md:px-8 md:py-10"><header className="flex items-center justify-between"><Link href="/discover" className="focus-ring inline-flex items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-foreground" data-testid="link-back-discover"><ArrowLeft size={17} /> Discover</Link><Link href="/profile" className="focus-ring grid h-10 w-10 place-items-center rounded-full border border-border bg-card text-sm font-semibold text-primary" data-testid="link-likes-profile">YO</Link></header>{children}</div></div>;
}

export default function LikesPage() {
  const likes = useGetMyLikes({ query: { queryKey: getGetMyLikesQueryKey() } });
  const matches = useGetMyMatches({ query: { queryKey: getGetMyMatchesQueryKey() } });
  if (likes.isLoading || matches.isLoading) return <LikesFrame><div className="mt-12 space-y-5"><div className="skeleton h-5 w-28 rounded" /><div className="skeleton h-16 w-2/3 rounded-xl" /><div className="grid gap-4 sm:grid-cols-3"><div className="skeleton h-48 rounded-2xl" /><div className="skeleton h-48 rounded-2xl" /><div className="skeleton h-48 rounded-2xl" /></div></div></LikesFrame>;
  if (likes.isError || matches.isError) return <LikesFrame><div className="mt-16 grid min-h-72 place-items-center rounded-3xl border border-destructive/30 bg-destructive/[.06] p-8 text-center"><div><CircleHelp className="mx-auto mb-3 text-destructive" size={30} /><h1 className="font-display text-2xl">Likes are out of reach</h1><p className="mt-2 text-sm text-muted-foreground">We could not retrieve your private signals.</p><button type="button" onClick={() => { void likes.refetch(); void matches.refetch(); }} className="focus-ring mt-5 rounded-xl border border-border px-4 py-3 text-sm font-semibold hover:border-primary" data-testid="button-retry-likes">Try again</button></div></div></LikesFrame>;
  const data = likes.data;
  const previews = data?.previews ?? [];
  const matchList = matches.data?.matches ?? [];
  return <LikesFrame><main className="mt-12 animate-rise"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="mb-3 flex items-center gap-2 font-mono-pulse text-[11px] uppercase tracking-[.2em] text-accent"><Heart size={13} fill="currentColor" /> Private signals</p><h1 className="font-display text-4xl font-semibold tracking-[-.06em] md:text-6xl">Who liked <span className="text-primary">you.</span></h1><p className="mt-4 max-w-lg text-[15px] leading-7 text-muted-foreground">A real count from the people who sent a signal your way. Photos stay blurred until the connection is mutual.</p></div><Link href="/discover" className="focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground" data-testid="link-return-discover"><Compass size={16} /> Discover people</Link></div>
    <section className="mt-10 rounded-3xl border border-accent/25 bg-accent/[.05] p-6 md:p-8"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-accent/15 text-accent"><Heart size={25} fill="currentColor" /></div><div><p className="font-mono-pulse text-[10px] uppercase tracking-[.18em] text-accent">Current count</p><p className="mt-1 font-display text-4xl">{data?.count ?? 0}</p></div></div>{previews.length === 0 ? <div className="mt-7 rounded-2xl border border-dashed border-border p-7 text-center"><Users className="mx-auto mb-3 text-muted-foreground" size={27} /><p className="font-display text-xl">No incoming signals yet.</p><p className="mt-2 text-sm text-muted-foreground">Your next meaningful connection should feel like a choice, not a queue.</p></div> : <div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{previews.map((preview) => <div key={preview.userId} className="relative overflow-hidden rounded-2xl border border-border bg-card" data-testid={`card-like-preview-${preview.userId}`}>{preview.photoPath ? <img src={mediaUrl(preview.photoPath)} alt="Blurred profile preview" className="aspect-[4/5] w-full object-cover blur-xl scale-110" /> : <div className="grid aspect-[4/5] place-items-center bg-muted"><UserRound className="text-muted-foreground" size={28} /></div>}<div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-black/55 px-3 py-2 text-sm font-semibold text-white"><span>{preview.firstInitial}.</span><span className="text-[10px] font-normal text-white/70">Blurred</span></div></div>)}</div>}</section>
    <section className="mt-10"><div className="flex items-end justify-between"><div><p className="mb-2 font-mono-pulse text-[11px] uppercase tracking-[.18em] text-secondary">Mutual signals</p><h2 className="font-display text-3xl">Matches</h2></div><span className="text-sm text-muted-foreground">{matchList.length} recorded</span></div>{matchList.length === 0 ? <div className="mt-4 rounded-2xl border border-dashed border-border p-8 text-center"><Sparkles className="mx-auto mb-3 text-muted-foreground" size={26} /><p className="font-display text-xl">Your matches will live here.</p><p className="mt-2 text-sm text-muted-foreground">When a heart is mutual, the signal will appear without inventing a conversation.</p></div> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{matchList.map((item) => <article key={item.id} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-4" data-testid={`card-match-${item.id}`}><div className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Heart size={20} fill="currentColor" /></div><div className="min-w-0 flex-1"><h3 className="font-display text-xl">{item.firstName}, {item.age}</h3><p className="mt-1 flex items-center gap-1.5 truncate text-xs text-muted-foreground"><MapPin size={12} /> {[item.region, item.country].filter(Boolean).join(', ') || 'Location private'}</p></div><div className="flex items-center gap-1.5 text-xs text-secondary"><BadgeCheck size={14} /> Matched</div></article>)}</div>}</section>
    <div className="mt-10 rounded-2xl border border-border bg-card p-5 text-sm leading-6 text-muted-foreground"><div className="flex gap-3"><MessageCircle className="mt-0.5 shrink-0 text-primary" size={17} /><p>Send Message and Icebreaker are intentionally held for Phase 3. PULSE records the match without sending anything on your behalf.</p></div></div>
  </main></LikesFrame>;
}